/**
 * Created by mohsom on 17.11.2014.
 */
module.exports=function(grunt){
    grunt.initConfig({
        pkg:grunt.file.readJSON("package.json"),
        jshint:{
            options:{
                curly:true,
                eqeqeq:true,
                immned:true,
                latedef:true,
                rewcap:true,
                roarg:true,
                sub:true,
                undef:true,
                eqnull:true,
                browser:true,
                globals:{
                    jQuery:true,
                    $:true,
                    console:true,
                    Backbone:true,
                    _:true
                }
            },
            "<%=pkg.name%>":{
                src:["js/models/*.js","js/collection/*.js","js/views/*.js"]
            }
        },
        concat:{
            options:{
                stripBanner:true,
                banner:"/*My project js file in <%=pkj.name%> version: <%=pkg.version%>*/"
            },
            dist:{
                 src:["js/models/link.js","js/collection/links.js","js/views/linkView.js","js/views/app.js","js/main.js"],
                 dist:"release/js/main.js"
            }
        }
    });
    grunt.loadNpmTasks("grunt-contrib-jshint");
    grunt.loadNpmTasks("grunt-contrib-concat");
    grunt.registerTask("default",["jshint","concat"]);
};