/**
 * Created by mohsom on 17.11.2014.
 */
module.exports=function(grunt){
    grunt.initConfig({
        pkg:grunt.file.readJSON("package.json"),
        jshint:{
            options:{
                curly:true,
                eqeqeq:true,
                immned:true,
                latedef:true,
                rewcap:true,
                roarg:true,
                sub:true,
                undef:true,
                eqnull:true,
                browser:true,
                globals:{
                    jQuery:true,
                    $:true,
                    console:true,
                    Backbone:true,
                    _:true
                }
            },
            "<%=pkg.name%>":{
                src:["js/models/*.js","js/collection/*.js","js/views/*.js"]
            }
        }
    });
    grunt.loadNpmTasks("grunt-contrib-jshint");
    grunt.registerTask("default",["jshint"]);
};